app:
  kafka:
    enabled: true

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      missing-topics-fatal: false
    streams:
      application-id: ${KAFKA_STREAMS_APP_ID:${KAFKA_STREAMS_APPLICATION_ID:eda-alerts-app}}
      replication-factor: 1
      properties:
        processing.guarantee: exactly_once_v2
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver