openapi: 3.0.3
info:
  title: EDA Backend API
  version: 0.1.0
paths:
  /api/hello:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
